services:
  - type: web
    name: my-flask-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && flask db upgrade"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT"
